=== kosssi/paheko-modules/saisie_poids/category.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"description": "Catégorie de sortie ou d'entrée (= provenance ou raison de sortie, vente, etc.)",
	"properties": {
		"type": {
			"type": "string",
			"enum": ["category"]
		},
		"label": {
			"description": "Libellé",
			"type": "string"
		},
		"target": {
			"type": "string",
			"enum": ["entry", "exit"]
		},
		"ecologic": {
			"description": "Position Ecologic",
			"type": ["string", "null"],
			"enum": ["PRE", "DEC_REE", "LIV"]
		}
	},
	"required": ["type", "label", "target", "ecologic"]
}

=== kosssi/paheko-modules/saisie_poids/defaults.json
[
	{
		"type": "category",
		"label": "Autre (particulier, déchètterie non conventionnée, etc.)",
		"ecologic": "LIV",
		"target": "entry"
	},
	{
		"type": "category",
		"label": "Déchètterie conventionnée Ecologic",
		"ecologic": "PRE",
		"target": "entry"
	},
	{
		"type": "category",
		"label": "Don magasin cycles",
		"ecologic": "LIV",
		"target": "entry"
	},
	{
		"type": "category",
		"label": "Vente de vélo",
		"ecologic": "DEC_REE",
		"target": "exit"
	},
	{
		"type": "category",
		"label": "Vente de pièce détachée",
		"ecologic": "DEC_REE",
		"target": "exit"
	},
	{
		"type": "category",
		"label": "Destruction",
		"ecologic": null,
		"target": "exit"
	},
	{
		"type": "category",
		"label": "Rachat de matériel",
		"ecologic": null,
		"target": "entry"
	},
	{
		"type": "object",
		"label": "Accessoire / pièce vélo",
		"weight": 600,
		"target": "entry"
	},
	{
		"type": "object",
		"label": "Vélo enfant",
		"weight": 10000,
		"target": "entry"
	},
	{
		"type": "object",
		"label": "Vélo adulte",
		"weight": 12500,
		"target": "entry"
	},
	{
		"type": "object",
		"label": "Trottinette, skateboard, roller",
		"weight": 4000,
		"target": "entry"
	}
]
